# Generated by Django 4.1.3 on 2022-11-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('SALES', 'Sales'), ('MARKE', 'Marketing'), ('ACCOU', 'Accounting'), ('MANUF', 'Manufacturing'), ('PLANN', 'Planning')], default='SALES', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sales_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
