# Generated by Django 4.1.3 on 2022-11-17 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=50, verbose_name='business')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('suite', models.CharField(blank=True, max_length=50, null=True, verbose_name='suite')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=10, null=True, verbose_name='state')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='zipcode')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='country')),
                ('website', models.CharField(blank=True, max_length=30, null=True, verbose_name='website')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('salesrep', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50, verbose_name='full name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_photos')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('cellphone', models.CharField(blank=True, max_length=50, null=True, verbose_name='cellphone')),
                ('office_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='office phone')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
