# Generated by Django 4.1.3 on 2022-11-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_country_alter_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='website'),
        ),
    ]
