# Generated by Django 4.1.3 on 2022-11-26 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_bookcontents_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontents',
            name='board',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.board'),
        ),
    ]
