# Generated by Django 4.1.3 on 2022-11-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_bookcontents_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontents',
            name='order_name',
            field=models.CharField(default='First', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookcontents',
            name='order_number',
            field=models.IntegerField(default=10),
        ),
    ]
