# Generated by Django 4.1.3 on 2022-11-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CBCT', 'Conebeam CT'), ('PANO', 'Panoramic'), ('CEPH', 'Cephalo')], default='CBCT', max_length=5),
        ),
    ]
